PORT = 5252

MAX_CONNECTIONS = 10

DEFAULT_ENCODING = 'utf-8'
DEFAULT_CLIENT_DB_PATH = './remote.db'
DEFAULT_SERVER_DB_PATH = './local.db'

REQUEST_CONNECT_HEADER = "CONN"
REQUEST_CLONE_HEADER = "CLONE"
REQUEST_REMOVE_HEADER = "REM"
REQUEST_ADD_HEADER = "ADD"
REQUEST_UPDATE_HEADER = "UPDATE"
REQUEST_RESET_HEADER = "RST"
REQUEST_ADD_USER_HEADER = "ADDU"
REQUEST_DEL_USER_HEADER = "DELU"
REQUEST_AUTHENTICATE_HEADER = "AUTH"
REQUEST_QUERY_HEADER = "QUER"
REQUEST_CONTENT_HEADER = "GET"
REQUEST_QUERY_FILTERS = {
    "Author": "AUTH",
    "Title": "TITL"
}

SEARCH_FILTER = {
    "AUTH": "author",
    "TITL": "title"
}

REQUEST_CONNECT = REQUEST_CONNECT_HEADER
REQUEST_AUTHENTICATE = REQUEST_AUTHENTICATE_HEADER + " %s %s"
REQUEST_QUERY = REQUEST_QUERY_HEADER + " %s %s"
REQUEST_QUERY_WAIT = REQUEST_QUERY_HEADER + " WAT"

REQUEST_GET_CONTENT = REQUEST_CONTENT_HEADER + " %d"

RESPONSE_CONNECT_APPROVED = REQUEST_CONNECT_HEADER + " APV"
RESPONSE_CONNECT_RESET = REQUEST_CONNECT_HEADER + " RST"
RESPONSE_AUTHENTICATE_OK = REQUEST_AUTHENTICATE_HEADER + " OK"
RESPONSE_AUTHENTICATE_WRONG_CREDS = REQUEST_AUTHENTICATE_HEADER + " WC"
RESPONSE_AUTHENTICATE_RESET = REQUEST_AUTHENTICATE_HEADER + " RST"
RESPONSE_QUERY_INFO = REQUEST_QUERY_HEADER + " %d"
RESPONSE_QUERY_LINE = REQUEST_QUERY_HEADER + " |%s|%s|%s"

RESPONSE_CONTENT_INFO = "%010d"

SQL_CREATE_USERS = "CREATE TABLE users (id INTEGER PRIMARY KEY, " \
                   "username VARCHAR, " \
                   "password VARCHAR, " \
                   "privilege INT)"
SQL_CREATE_GENRES = "CREATE TABLE genres (id INT AUTO_INCREMENT, " \
                    "title VARCHAR)"
SQL_CREATE_BOOKS = "CREATE TABLE books (id INTEGER PRIMARY KEY, " \
                   "title VARCHAR, " \
                   "genres TEXT, " \
                   "text NTEXT, " \
                   "author NTEXT)"
SQL_LOGIN = "SELECT * FROM users WHERE username=? AND password=?"
SQL_SIGNUP = "INSERT INTO users (username, password, privilege) VALUES (?, ?, ?)"
SQL_ADD_GENRE = "INSERT INTO genres (title) VALUES (?)"
SQL_GET_GENRE_TITLE = "SELECT title FROM genres WHERE id=?"
SQL_GET_GENRE_ID = "SELECT id FROM genres WHERE title=?"
SQL_ADD_BOOK = "INSERT INTO books (title, text, genres, author) VALUES (?, ?, ?, ?)"
SQL_GET_BOOKS = "SELECT * FROM books WHERE %s LIKE ?"
SQL_GET_CONTENT = "SELECT text FROM books WHERE id=?"

BANNER = '''
 Welcome to SnakeEyes!
by ArturLukianov

/---\\
| 0 |
\\___/

Please, use API or join SnakeEyes community to develop server UI

* No multithreading
* No connection encryption
* Client only reading channel enabled


Enjoy new information!
'''
